# Generated by Django 5.0.1 on 2026-02-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_level_category_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/'),
        ),
    ]
